//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CUENTAS_POR_PAGAR1
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACTURASSAMBOY
    {
        public int NUMEROFACTURA { get; set; }
        public string CODIGO { get; set; }
        public Nullable<decimal> VALORFACTURA { get; set; }
        public Nullable<System.DateTime> FECHAFACTURA { get; set; }
        public Nullable<System.DateTime> FECHAVENCIMIENTO { get; set; }
    }
}
